typography_spectrum: 0.405
color:
  brandColors:
    - '#e1e1e1'
    - '#636361'
    - '#fffeff'
    - '#2f2f2f'
    - '#2e2e2e'
  brandStrength: 0.75
  lightness: 0.1875
  saturation: 0
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.67427
analytics:
  google: null
  facebook: null
  twitter: null
name: Instagram_shares
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: INSTAGRAM
description: SHARES
purpose: []
