name: Instagram_shares
favicon: null
layout_spectrum: 0.67427
typography_spectrum: 0.405
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e1e1e1'
    - '#636361'
    - '#fffeff'
    - '#2f2f2f'
    - '#2e2e2e'
  brandStrength: 1
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0
purpose: []
