name: Instagram_shares
favicon: null
layout_spectrum: 0.07500937161967158
typography_spectrum: 0.26921903993934393
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8916443546768278
  lightness: 0.20045786281116307
  saturation: 0.4437629468739033
  rhythmicContrast: 0.97769481735304
purpose: []
